### ISSUE TITLE
Add custom app logo

### ISSUE THREAD

**Issue by ErikP0** [ErikP0/sheepshead-manager#13]

**Comment by BlackWhiteOrbit** [comment]
Logo schaut gut aus. Wenn es funktionsfähig ist, gilt es somit als reviewed. 
Bitte gleich überall implementieren als "unser" Logo.

**Comment by ErikP0** [comment]
Erste Version ist jetzt auf dem Master, ich lass das Issue mal offen. Wenn jemanden grad die Muse geküsst hat, kann er ja noch ein besseres Logo machen :smiley:

**Comment by BlackWhiteOrbit** [comment]
App logo ist voll zufriedenstellend. Die wird ja nur von uns selbst verwendet, daher schließe ich mal das thema ;)
