### ISSUE TITLE
Create Startbildschirm

### ISSUE THREAD

**Issue by BlackWhiteOrbit** [ErikP0/sheepshead-manager#16]
Hier sollten einfache Buttons mit den Funktionalitäten Beenden, Neue Sitzung erstellen, Alte Sitzung laden angebracht werden. Sowie ein Logo.

Evtl. sollte das auch zu Mile 2 verschoben werden.

**Comment by BlackWhiteOrbit** [comment]
Bitte auch die überarbeitete draft.tex anstehen und wenn annehmbar, bitte mergen!

**Comment by ErikP0** [comment]
Den branch mit der überarbeiteten draft.tex hab ich in den master gemerged. Ich denke enhancement-Labels sind dafür da, optionale Funktionalitäten zu beschreiben. Ich habe deshalb ein paar enhancement-Labels von den wichtigen Punkten aus Meilenstein 2 entfernt.
