### ISSUE TITLE
ScoreBoard/List/Table

### ISSUE THREAD

**Issue by ErikP0** [ErikP0/sheepshead-manager#19]
Modell zum Speichern mehrerer SingleGameResults

**Comment by BlackWhiteOrbit** [comment]
Wird eigentlich dachte ich in Session schon übernommen. Da habe ich eine Matrix, die die ganzen Geldbeträge speichert. Oder meinst du Scoreboard als die Gui? Das wäre natürlich wichtig da noch eine anzeige zu haben.

**Comment by ErikP0** [comment]
Das Scoreboard als Gui ist ein extra Issue (#18). Das kann in der Session auch übernommen werden, tagge einfach die Commits die gemacht werden auch mit dieser Issue-Nr.

**Comment by BlackWhiteOrbit** [comment]
Also als gui wäre es schon noch wichtig. ;)
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.On 08/10/2016, 11:33 ErikP0 <notifications@github.com> wrote:

  
    
      Das Scoreboard als Gui ist ein extra Issue (#18). Das kann in der Session auch übernommen werden, tagge einfach die Commits die gemacht werden auch mit dieser Issue-Nr.

**Comment by ErikP0** [comment]
Implemented in #18
