### ISSUE TITLE
FillInGameResult-Activity

### ISSUE THREAD

**Issue by ErikP0** [ErikP0/sheepshead-manager#4]

**Comment by ErikP0** [comment]
In Review

**Comment by BlackWhiteOrbit** [comment]
Reviewed:

Schaut gut aus. Nur kein Spiel ausgewählt, sollte vollständig lesbar sein.

Wenn Sie oder Tout ausgewählt wird, darf das andere nicht mehr ausgewählt werden.

Verbesserungen:

Es sollte das ausgewählte Spiel, durch z.B. eine andere Buttonfarbe signalisiert werden. 
Es sollte nicht für jeden Spieler einzeln ausgewählt werden müssen, sondern evtl. erst danach die Frage kommen, welche spieler gewonnen haben. Z.b. bei einem Sauspiel Spieler 2 und 5 (die Spieler werden in der Session festgelegt). Und der Rest wird dann ermittelt. 

Also in der Maske wirklich nur quasi die Auswahl die StakeModifier entspricht. Dann werden die Spieler gesettet. Wobei natürlich die Namen und Nummern nur einmal erstellt werden pro Sitzung. Und dann lässt sich auch problemlos die SingleGameResult Methoden aufrufen und ein Spiel lässt sich erstellen.

Vlt könntest du das noch heute schaffen? Dann könnten wir, wenn meines so passt mal die ganzen hauptteile mergen, um mal ne breitere Basis zum arbeiten zu haben.

**Comment by BlackWhiteOrbit** [comment]
Bitte noch die kleinen Verbesserungen integrieren. Ich werde die logikklassen bei entsprechender zustimmung dann noch vor mitternacht hochladen.

**Comment by ErikP0** [comment]
Sorry hatte gar nicht gesehen, dass du nochmal drübergeschaut hast.
