### ISSUE TITLE
Classes for Player, Stake, GameType & GameResult

### ISSUE THREAD

**Issue by ErikP0** [ErikP0/sheepshead-manager#5]

**Comment by ErikP0** [comment]
Review:
- Bennenung: 
 - Paketname `SingleGameRequirements` klein (per Java-Konvention, kein Camel/Pascalcase) und nicht als sub-Paket von `main` (1 Ebene höher).
 - `ConstantsForSheepshead` umstellen, "for" gehört in keinen Klassennamen, besser z.B. `SheepsheadConstants`
 - `Player.isHasWon()` würde ich zu `Player.hasWon()` umschreiben
- `GameType`: Wenn alle Enum-Deklarationen den Konstruktor mit den 2 ints verwenden (sollen), sollte der default-Konstruktor nicht definiert sein.
- `Player`:
 - `playername` u. `playernumber`: Da die Klasse Player heißt, dürfte `name` bzw. `number` auch klar sein
 - `isPlayer`: Sollte umbenannt werden, player meint ja nicht nur den Spieler (im Sinne von Schafkopf: Spieler, der die Ansage gemacht hat) sondern könnte auch Teilnehmer am Schafkopfspiel oder sogar als eine Art `typeof/instanceof` verstanden werden.
 - Attribut `playernumber` braucht wahrscheinlich keinen setter, da sie sich im Verlauf des Spiels nicht ändern wird
 - `Player` repräsentiert einen Teilnehmer, nicht seinen Kontostand und sollte daher kein `priceToGet` haben. Spätestens in Meilenstein 2 wird es so einen Kontostand geben müssen, das in einem Spiel erzielte Geld sollte eher in `SingleGameResult` (z.B. in einer Map) gespeichert werden
- `SingleGameResult`: `participatoryPlayers` könnte nach `participatingPlayers` oder `participants` umbenannt werden.

`SingleGameResult` und `Stake` haben ziemlich viel Code mit der gleichen Funktionalität (z.B. kontra/re/tout/sie/schneider/schwarz/laufende). Das sollte in eine Klasse rausgezogen werden (z.B in `StakeModifier`). M.M.n. sollte `Stake` eine andere Funktionalität haben: Nämlich Stake im Sinne von Spieleinsatz (also 10 für Sauspiel, 50 für Solo, usw) statt als ausgeschüttetes Ergebnis von einem Spiel. Die erste Funktionalität erfüllt im Prinzip `ConstantsForSheepshead`, die letztere kann auch als Attribut in `SingleGameResult` leben. Die Berechnung (anhand des Spieltyps und der `StakeModifier`) kann ebenso in `SingleGameResult` stattfinden.

Zu den Tests:
- `StakeTest.whenSetStakeIsExecuted(...)` kann `private` sein
- `SingleGameResultTest.whenSetSingleGameResultIsExecuted()` enthält genau eine Instruktion, kann vllt weggelassen werden?

**Comment by BlackWhiteOrbit** [comment]
Hi Erik,

Also Namen werde ich alle ändern,

Das Geld, das ein Spieler besitzt ist nicht ohne weiteres auslagerbar in Single game result. Da ja jeder Spieler ebenfalls einen aktuellen kontostand besitzt und die Spieler genau einmal initialisiert werden sollen. 
Das Ergebnis aller spiele würde dann entsprechend z.B. in einer Matrix repräsentiert werden. Eine Zeile wäre dann SingleGameResult und ja da wird es noch entsprechende Unternehmungen geben. Das richtig zustellen.

Ich habe stake als aktuellen Spiel Einsatz verstanden. Wenn du das aber nicht in einer eigene klasse haben willst, integriere ich das in SingleGameResult und würde dann Stake komplett entfernen. 
Was ein sauspiel wert ist, sollte meiner Meinung nach eine konstante sein. Wir werden das vermutlich nicht ändern für unsere Funktionalität.

In GameType entferne ich den Konstruktor. 

Prinzipiell gilt bei Methoden. Redundante Methoden , wie getter und setter, sowie Methoden,  die eine struktur oder Hierarchie darstellen (given, when, then) sollten lieber im Code stehen. 

Es erhöht 1. Die Übersicht.
2. Evtl. Werden diese in Zukunft gebraucht. 

Genauso verhält es sich mit Klassen und Interfaces.

Lieber so abstrakt wie möglich und so wenig wie nötig in eine klasse.

LG
Nico
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.On 06/10/2016, 15:19 ErikP0 <notifications@github.com> wrote:

  
    
      Review:
    
    
      
        Bennenung:
        
          
            Paketname SingleGameRequirements klein (per Java-Konvention, kein Camel/Pascalcase) und nicht als sub-Paket von main (1 Ebene höher).
          
          
            ConstantsForSheepshead umstellen, "for" gehört in keinen Klassennamen, besser z.B. SheepsheadConstants
          
          
            Player.isHasWon() würde ich zu Player.hasWon() umschreiben
          
        
      
      
        GameType: Wenn alle Enum-Deklarationen den Konstruktor mit den 2 ints verwenden (sollen), sollte der default-Konstruktor nicht definiert sein.
      
      
        Player:
        
          
            playername u. playernumber: Da die Klasse Player heißt, dürfte name bzw. number auch klar sein
          
          
            isPlayer: Sollte umbenannt werden, player meint ja nicht nur den Spieler (im Sinne von Schafkopf: Spieler, der die Ansage gemacht hat) sondern könnte auch Teilnehmer am Schafkopfspiel oder sogar als eine Art typeof/instanceof verstanden werden.
          
          
            Attribut playernumber braucht wahrscheinlich keinen setter, da sie sich im Verlauf des Spiels nicht ändern wird
          
          
            Player repräsentiert einen Teilnehmer, nicht seinen Kontostand und sollte daher kein priceToGet haben. Spätestens in Meilenstein 2 wird es so einen Kontostand geben müssen, das in einem Spiel erzielte Geld sollte eher in SingleGameResult (z.B. in einer Map) gespeichert werden
          
        
      
      
        SingleGameResult: participatoryPlayers könnte nach participatingPlayers oder participants umbenannt werden.
      
    
    
      SingleGameResult und Stake haben ziemlich viel Code mit der gleichen Funktionalität (z.B. kontra/re/tout/sie/schneider/schwarz/laufende). Das sollte in eine Klasse rausgezogen werden (z.B in StakeModifier). M.M.n. sollte Stake eine andere Funktionalität haben: Nämlich Stake im Sinne von Spieleinsatz (also 10 für Sauspiel, 50 für Solo, usw) statt als ausgeschüttetes Ergebnis von einem Spiel. Die erste Funktionalität erfüllt im Prinzip ConstantsForSheepshead, die letztere kann auch als Attribut in SingleGameResult leben. Die Berechnung (anhand des Spieltyps und der StakeModifier) kann ebenso in SingleGameResult stattfinden.
    
    
      Zu den Tests:
    
    
      
        StakeTest.whenSetStakeIsExecuted(...) kann private sein
      
      
        SingleGameResultTest.whenSetSingleGameResultIsExecuted() enthält genau eine Instruktion, kann vllt weggelassen werden?

**Comment by ErikP0** [comment]
Nochmal eine Klarstellung zu den gettern/settern. Ich hab prinzipiell nichts dagegen. Ich meinte hier mit Redundanz nicht, dass da immer getx(), setx() steht, sondern vielmehr, dass beide Klassen Werte für schneider, schwarz ,kontra, re, tout, sie und die laufenden speichern. Das muss nicht sein. Daher mein Vorschlag mit `StakeModifier`, der alle schneider, schwarz, ..., sie und die laufende mit getter/setter speichert und dann jeweils als Attribut in `SingleGameResult` bzw. `Stake` (wenn es das so noch gibt) gespeichert wird.

**Comment by BlackWhiteOrbit** [comment]
Alles entsprechend ausgebessert und Unittests überarbeitet. Da ich ein ungefähres Konstrukt für die Logik im Kopf habe würde ich das jetzt erstmal so belassen. Die Funktionalitäten der Klassen sollten denk ich klar sein. Evtl ändere ich später Kleinigkeiten.
