### ISSUE TITLE
Use stake calculation model in FillGameResultActivity

### ISSUE THREAD

**Issue by ErikP0** [ErikP0/sheepshead-manager#7]

**Comment by BlackWhiteOrbit** [comment]
Es steht in FillGameResult in Zeile 215         CheckBox boxCallerSideWon = findView(R.id.FillGameResult_checkbox_callerside_won);

checkbox_callerside_won existiert aber nicht, sondern nur playerside won, daher werde ich den Namen in der id ändern. und es dann testen. Wenn es klappt merge ich dann

**Comment by BlackWhiteOrbit** [comment]
Done
